apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-enable-multipathing
spec:
  config:
    ignition: 
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,ICBkZWZhdWx0cyB7CiAgICAgICAgcG9sbGluZ19pbnRlcnZhbCAxMAogICAgICAgIGZpbmRfbXVsdGlwYXRocyAieWVzIgp9CmRldmljZXMgewogIGRldmljZSB7CiAgICAgICAgdmVuZG9yICJQVVJFIgogICAgICAgIHByb2R1Y3QgIkZsYXNoQXJyYXkiCiAgICAgICAgZmFzdF9pb19mYWlsX3RtbyAxMAogICAgICAgIHBhdGhfZ3JvdXBpbmdfcG9saWN5ICJncm91cF9ieV9wcmlvIgogICAgICAgIGZhaWxiYWNrICJpbW1lZGlhdGUiCiAgICAgICAgcHJpbyAiYWx1YSIKICAgICAgICBoYXJkd2FyZV9oYW5kbGVyICIxIGFsdWEiCiAgICAgICAgbWF4X3NlY3RvcnNfa2IgNDA5NgogICAgfQp9Cg==
        filesystem: root
        mode: 420
        path: /etc/multipath.conf
    systemd:
      units:
      - name: multipathd.service
        enabled: true
