apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-enable-multipathing
spec:
  config:
    ignition: 
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewoJdXNlcl9mcmllbmRseV9uYW1lcyBubwoJZmluZF9tdWx0aXBhdGhzIHllcwoJZW5hYmxlX2ZvcmVpZ24gIl4kIgogICAgICAgIHBvbGxpbmdfaW50ZXJ2YWwgICAxMAp9CgpkZXZpY2VzIHsKICAgIGRldmljZSB7CiAgICAgICAgdmVuZG9yICAgICAgICAgICAgICAgICAgICAgICJOVk1FIgogICAgICAgIHByb2R1Y3QgICAgICAgICAgICAgICAgICAgICAiUHVyZSBTdG9yYWdlIEZsYXNoQXJyYXkiCiAgICAgICAgcGF0aF9zZWxlY3RvciAgICAgICAgICAgICAgICJxdWV1ZS1sZW5ndGggMCIKICAgICAgICBwYXRoX2dyb3VwaW5nX3BvbGljeSAgICAgICAgZ3JvdXBfYnlfcHJpbwogICAgICAgIHByaW8gICAgICAgICAgICAgICAgICAgICAgICBhbmEKICAgICAgICBmYWlsYmFjayAgICAgICAgICAgICAgICAgICAgaW1tZWRpYXRlCiAgICAgICAgZmFzdF9pb19mYWlsX3RtbyAgICAgICAgICAgIDEwCiAgICAgICAgdXNlcl9mcmllbmRseV9uYW1lcyAgICAgICAgIG5vCiAgICAgICAgbm9fcGF0aF9yZXRyeSAgICAgICAgICAgICAgIDAKICAgICAgICBmZWF0dXJlcyAgICAgICAgICAgICAgICAgICAgMAogICAgICAgIGRldl9sb3NzX3RtbyAgICAgICAgICAgICAgICA2MAogICAgICAgIGZpbmRfbXVsdGlwYXRocyAgICAgICAgICAgICB5ZXMKICAgIH0KICAgIGRldmljZSB7CiAgICAgICAgdmVuZG9yICAgICAgICAgICAgICAgICAgICJQVVJFIgogICAgICAgIHByb2R1Y3QgICAgICAgICAgICAgICAgICAiRmxhc2hBcnJheSIKICAgICAgICBwYXRoX3NlbGVjdG9yICAgICAgICAgICAgInNlcnZpY2UtdGltZSAwIgogICAgICAgIGhhcmR3YXJlX2hhbmRsZXIgICAgICAgICAiMSBhbHVhIgogICAgICAgIHBhdGhfZ3JvdXBpbmdfcG9saWN5ICAgICBncm91cF9ieV9wcmlvCiAgICAgICAgcHJpbyAgICAgICAgICAgICAgICAgICAgIGFsdWEKICAgICAgICBmYWlsYmFjayAgICAgICAgICAgICAgICAgaW1tZWRpYXRlCiAgICAgICAgcGF0aF9jaGVja2VyICAgICAgICAgICAgIHR1cgogICAgICAgIGZhc3RfaW9fZmFpbF90bW8gICAgICAgICAxMAogICAgICAgIHVzZXJfZnJpZW5kbHlfbmFtZXMgICAgICBubwogICAgICAgIG5vX3BhdGhfcmV0cnkgICAgICAgICAgICAwCiAgICAgICAgZmVhdHVyZXMgICAgICAgICAgICAgICAgIDAKICAgICAgICBkZXZfbG9zc190bW8gICAgICAgICAgICAgNjAwCiAgICAgICAgZmluZF9tdWx0aXBhdGhzICAgICAgICAgIHllcwogICAgfQp9CgpibGFja2xpc3RfZXhjZXB0aW9ucyB7CiAgICAgICAgcHJvcGVydHkgIihTQ1NJX0lERU5UX3xJRF9XV04pIgp9CgpibGFja2xpc3QgewogICAgICBkZXZub2RlICJecHhkWzAtOV0qIgogICAgICBkZXZub2RlICJecHhkKiIKICAgICAgZGV2aWNlIHsKICAgICAgICB2ZW5kb3IgIlZNd2FyZSIKICAgICAgICBwcm9kdWN0ICJWaXJ0dWFsIGRpc2siCiAgICAgIH0KfQ==
        path: /etc/multipath.conf
      - contents:
          source: data:,I0FDVElPTj09Y2hhbmdlLCBTVUJTWVNURU09PXNjc2ksIEVOVntTREVWX1VBfT09SU5RVUlSWV9EQVRBX0hBU19DSEFOR0VELCBURVNUPT1yZXNjYW4sIEFUVFJ7cmVzY2FufT14CkFDVElPTj09Y2hhbmdlLCBTVUJTWVNURU09PXNjc2ksIEVOVntTREVWX1VBfT09Q0FQQUNJVFlfREFUQV9IQVNfQ0hBTkdFRCwgVEVTVD09cmVzY2FuLCBBVFRSe3Jlc2Nhbn09eAojQUNUSU9OPT1jaGFuZ2UsIFNVQlNZU1RFTT09c2NzaSwgRU5We1NERVZfVUF9PT1USElOX1BST1ZJU0lPTklOR19TT0ZUX1RIUkVTSE9MRF9SRUFDSEVELCBURVNUPT1yZXNjYW4sIEFUVFJ7cmVzY2FufT14CiNBQ1RJT049PWNoYW5nZSwgU1VCU1lTVEVNPT1zY3NpLCBFTlZ7U0RFVl9VQX09PU1PREVfUEFSQU1FVEVSU19DSEFOR0VELCBURVNUPT1yZXNjYW4sIEFUVFJ7cmVzY2FufT14CkFDVElPTj09Y2hhbmdlLCBTVUJTWVNURU09PXNjc2ksIEVOVntTREVWX1VBfT09UkVQT1JURURfTFVOU19EQVRBX0hBU19DSEFOR0VELCBSVU4rPXNjYW4tc2NzaS10YXJnZXQge0RFVlBBVEh9Cg==
        filesystem: root
        mode: 0644
        overwrite: true
        path: /etc/udev/rules.d/99-pure-storage.rules  
    systemd:
      units:
      - name: multipathd.service
        enabled: true
# The above manifest enabled multipathing for FiberChannel based connections. To add iSCSI based FlashArray's uncomment the two lines below to enable the iSCSI service in RHCOS.
      - name: iscsid.service
        enabled: true
        
