apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-enable-multipathing
spec:
  config:
    ignition: 
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,I0FDVElPTj09ImNoYW5nZSIsIFNVQlNZU1RFTT09InNjc2kiLCBFTlZ7U0RFVl9VQX09PSJJTlFVSVJZX0RBVEFfSEFTX0NIQU5HRUQiLCBURVNUPT0icmVzY2FuIiwgQVRUUntyZXNjYW59PSJ4IgpBQ1RJT049PSJjaGFuZ2UiLCBTVUJTWVNURU09PSJzY3NpIiwgRU5We1NERVZfVUF9PT0iQ0FQQUNJVFlfREFUQV9IQVNfQ0hBTkdFRCIsIFRFU1Q9PSJyZXNjYW4iLCBBVFRSe3Jlc2Nhbn09IngiCiNBQ1RJT049PSJjaGFuZ2UiLCBTVUJTWVNURU09PSJzY3NpIiwgRU5We1NERVZfVUF9PT0iVEhJTl9QUk9WSVNJT05JTkdfU09GVF9USFJFU0hPTERfUkVBQ0hFRCIsIFRFU1Q9PSJyZXNjYW4iLCBBVFRSe3Jlc2Nhbn09IngiCiNBQ1RJT049PSJjaGFuZ2UiLCBTVUJTWVNURU09PSJzY3NpIiwgRU5We1NERVZfVUF9PT0iTU9ERV9QQVJBTUVURVJTX0NIQU5HRUQiLCBURVNUPT0icmVzY2FuIiwgQVRUUntyZXNjYW59PSJ4IgpBQ1RJT049PSJjaGFuZ2UiLCBTVUJTWVNURU09PSJzY3NpIiwgRU5We1NERVZfVUF9PT0iUkVQT1JURURfTFVOU19EQVRBX0hBU19DSEFOR0VEIiwgUlVOKz0ic2Nhbi1zY3NpLXRhcmdldCAkZW52e0RFVlBBVEh9Ig==
        filesystem: root
        mode: 0644
        overwrite: true
        path: /etc/udev/rules.d/99-pure-storage.rules
      - contents:
          source: data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewoJdXNlcl9mcmllbmRseV9uYW1lcyBubwoJZW5hYmxlX2ZvcmVpZ24gIl4kIgogICAgICAgIHBvbGxpbmdfaW50ZXJ2YWwgICAgMTAKICAgICAgICBmaW5kX211bHRpcGF0aHMgeWVzCn0KCmRldmljZXMgewogICAgZGV2aWNlIHsKICAgICAgICB2ZW5kb3IgICAgICAgICAgICAgICAgICAgICAgIk5WTUUiCiAgICAgICAgcHJvZHVjdCAgICAgICAgICAgICAgICAgICAgICJQdXJlIFN0b3JhZ2UgRmxhc2hBcnJheSIKICAgICAgICBwYXRoX3NlbGVjdG9yICAgICAgICAgICAgICAgInF1ZXVlLWxlbmd0aCAwIgogICAgICAgIHBhdGhfZ3JvdXBpbmdfcG9saWN5ICAgICAgICBncm91cF9ieV9wcmlvCiAgICAgICAgcHJpbyAgICAgICAgICAgICAgICAgICAgICAgIGFuYQogICAgICAgIGZhaWxiYWNrICAgICAgICAgICAgICAgICAgICBpbW1lZGlhdGUKICAgICAgICBmYXN0X2lvX2ZhaWxfdG1vICAgICAgICAgICAgMTAKICAgICAgICB1c2VyX2ZyaWVuZGx5X25hbWVzICAgICAgICAgbm8KICAgICAgICBub19wYXRoX3JldHJ5ICAgICAgICAgICAgICAgMAogICAgICAgIGZlYXR1cmVzICAgICAgICAgICAgICAgICAgICAwCiAgICAgICAgZGV2X2xvc3NfdG1vICAgICAgICAgICAgICAgIDYwCiAgICB9CiAgICBkZXZpY2UgewogICAgICAgIHZlbmRvciAgICAgICAgICAgICAgICAgICAiUFVSRSIKICAgICAgICBwcm9kdWN0ICAgICAgICAgICAgICAgICAgIkZsYXNoQXJyYXkiCiAgICAgICAgcGF0aF9zZWxlY3RvciAgICAgICAgICAgICJzZXJ2aWNlLXRpbWUgMCIKICAgICAgICBoYXJkd2FyZV9oYW5kbGVyICAgICAgICAgIjEgYWx1YSIKICAgICAgICBwYXRoX2dyb3VwaW5nX3BvbGljeSAgICAgZ3JvdXBfYnlfcHJpbwogICAgICAgIHByaW8gICAgICAgICAgICAgICAgICAgICBhbHVhCiAgICAgICAgZmFpbGJhY2sgICAgICAgICAgICAgICAgIGltbWVkaWF0ZQogICAgICAgIHBhdGhfY2hlY2tlciAgICAgICAgICAgICB0dXIKICAgICAgICBmYXN0X2lvX2ZhaWxfdG1vICAgICAgICAgMTAKICAgICAgICB1c2VyX2ZyaWVuZGx5X25hbWVzICAgICAgbm8KICAgICAgICBub19wYXRoX3JldHJ5ICAgICAgICAgICAgMAogICAgICAgIGZlYXR1cmVzICAgICAgICAgICAgICAgICAwCiAgICAgICAgZGV2X2xvc3NfdG1vICAgICAgICAgICAgIDYwMAogICAgfQp9CgpibGFja2xpc3RfZXhjZXB0aW9ucyB7CiAgICAgICAgcHJvcGVydHkgIihTQ1NJX0lERU5UX3xJRF9XV04pIgp9CgpibGFja2xpc3QgewogICAgICBkZXZub2RlICJecHhkWzAtOV0qIgogICAgICBkZXZub2RlICJecHhkKiIKICAgICAgZGV2aWNlIHsKICAgICAgICB2ZW5kb3IgIlZNd2FyZSIKICAgICAgICBwcm9kdWN0ICJWaXJ0dWFsIGRpc2siCiAgICAgIH0KfQo=
        filesystem: root
        mode: 0644
        overwrite: true
        path: /etc/multipath.conf
    systemd:
      units:
      - name: multipathd.service
        enabled: true
# The above manifest enabled multipathing for FiberChannel based connections. To add iSCSI based FlashArray's uncomment the two lines below to enable the iSCSI service in RHCOS.
      - name: iscsid.service
        enabled: true
        
